
services:
    redis:
        image: redis:7.2-alpine
        container_name: redis
        networks:
            - health-net

    db:
        container_name: db
        image: postgres:16.3-alpine
        volumes:
            - ./health/data/db:/var/lib/postgresql/data
        labels:
            - app_label.model_name=postgres
        environment:
            - POSTGRES_DB=${DB:-db}
            - POSTGRES_DB_NAME=${DB_NAME:-db}
            - POSTGRES_USER=${DB_USER:-postgres}
            - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
        networks:
            - health-net

    mosquitto:
        image: eclipse-mosquitto:2.0
        hostname: mosquitto
        container_name: mosquitto
        ports:
            - "1883:1883"
        volumes:
            - ./health/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
        networks:
            - health-net

    app:
        container_name: app
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./health:/health/
        ports:
            - "8000:8000"
        environment:
            - POSTGRES_DB=${DB:-db}
            - POSTGRES_DB_NAME=${DB_NAME:-db}
            - POSTGRES_USER=${DB_USER:-postgres}
            - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
        depends_on:
            - db
            - redis
            - mosquitto
        networks:
            - health-net
        links:
            - db:db

networks:
    health-net: