apiVersion: v1
kind: Pod
metadata:
  name: health-pod
spec:
  containers:
    - name: redis
      image: docker.io/library/redis:7.2-alpine

    - name: db
      image: docker.io/library/postgres:16.3-alpine
      ports:
        - containerPort: 5432
          hostPort: 5432
      env:
        - name: POSTGRES_DB
          value: "db"
        - name: POSTGRES_DB_NAME
          value: "db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data

    - name: mosquitto
      image: docker.io/eclipse-mosquitto:2.0
      ports:
        - containerPort: 1883
          hostPort: 1883
      volumeMounts:
        - mountPath: /mosquitto/config/mosquitto.conf
          name: mosquitto-conf

    - name: app
      image: localhost/health-app:latest  # imagen buildeada localmente
      ports:
        - containerPort: 8000
          hostPort: 8000
      env:
        - name: POSTGRES_DB
          value: "db"
        - name: POSTGRES_DB_NAME
          value: "db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
      volumeMounts:
        - mountPath: /health
          name: app-data

  volumes:
    - name: db-data
      hostPath:
        path: ./health/data/db
        type: DirectoryOrCreate
    - name: mosquitto-conf
      hostPath:
        path: ./health/mosquitto/mosquitto.conf
        type: File
    - name: app-data
      hostPath:
        path: ./health
        type: Directory