# Generated by Django 6.0.3 on 2026-03-07 12:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bed', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('bed_state', models.CharField(default='free', max_length=30)),
                ('occupied_time', models.DateTimeField(blank=True, null=True)),
                ('planed_vacate', models.DateTimeField(blank=True, null=True)),
                ('vacate_time', models.DateTimeField(blank=True, null=True)),
                ('action_done_by', models.CharField(default='Anónimo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sin Nombre', max_length=50)),
                ('id_card_number', models.CharField(default='00000', max_length=50, null=True)),
                ('social_security_number', models.CharField(default='0000', max_length=50, null=True)),
                ('image', models.ImageField(blank=True, default='useravatar.png', null=True, upload_to='')),
                ('inpatient', models.BooleanField(default=True)),
                ('admission', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.TextField(default='Sin Diagnóstico')),
                ('short_diagnosis', models.TextField(default='Sin Diagnóstico')),
                ('treatment_roadmap', models.TextField(default='Sin Tratamiento')),
                ('action_done_by', models.CharField(default='Anónimo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loged_user', models.CharField(default='User', max_length=50)),
                ('action', models.CharField(default='No Action', max_length=50)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('before', models.CharField(default='No Before', max_length=1000)),
                ('after', models.CharField(default='No After', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('image', models.ImageField(blank=True, default='useravatar.png', null=True, storage=django.core.files.storage.FileSystemStorage(location='nursing/media'), upload_to='')),
                ('is_leader', models.BooleanField(blank=True, default=False, null=True)),
                ('role', models.CharField(default='nurse', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(default='Resapuesta sin novedad')),
                ('call_time', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(default='active', max_length=20)),
                ('action_done_by', models.CharField(default='Anónimo', max_length=50)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_bed', to='nursing.bed')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record_id', models.CharField(max_length=50, null=True)),
                ('medical_record_file', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='nursing/medicalrecords'), upload_to='')),
                ('action_done_by', models.CharField(default='Anónimo', max_length=50)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record_patient', to='nursing.patient')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='bed_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bed_patient', to='nursing.patient'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat', models.BooleanField(default=False)),
                ('repeat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('repeat_lapse', models.IntegerField(blank=True, null=True)),
                ('repeat_lapse_unit', models.CharField(blank=True, choices=[('minutes', 'Minutos'), ('hours', 'Horas'), ('days', 'Días')], max_length=20, null=True)),
                ('repeat_until', models.DateTimeField(blank=True, null=True)),
                ('task', models.TextField(default='Tarea de Rutina')),
                ('programed_time', models.DateTimeField(blank=True, null=True)),
                ('done_time', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('state', models.CharField(default='soon', max_length=15)),
                ('programed_by', models.CharField(default='Anónimo', max_length=50)),
                ('task_done_by', models.CharField(default='Pendiente', max_length=50)),
                ('action_done_by', models.CharField(default='Anónimo', max_length=50)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_bed', to='nursing.bed')),
            ],
        ),
    ]
