# Generated by Django 6.0.3 on 2026-03-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Event',
        ),
    ]
