"""
Django settings for healthproject project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# for enviroment variables 
import environ

# Initialise environment variables
env = environ.Env()
environ.Env.read_env()

import mimetypes
mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("text/html", ".html", True)
mimetypes.add_type("text/javascript", ".js", True)
mimetypes.add_type("image/vnd.microsoft.icon", ".ico", True)
mimetypes.add_type("image/svg+xml", ".svg", True)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY', default='myrealsecretkey')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False #env.bool('DEBUG', default=True)

ALLOWED_HOSTS = tuple(env.list('ALLOWED_HOSTS', default=['*']))
CORS_ORIGIN_WHITELIST = ('localhost:8000')
CORS_ORIGIN_ALLOW_ALL = True

# Login accounts/login to /login
LOGIN_URL = '/login' # '/nursing/login'




# Application definition

INSTALLED_APPS = [
    'daphne', # channels, daphne
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'nursing',
    "nursing_react",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'healthproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'nursing_react/build')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#WSGI_APPLICATION = 'healthproject.wsgi.wsgi_application'
ASGI_APPLICATION = 'healthproject.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(env.str('REDIS', default='redis'), 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env.str('DB_NAME', default='db'),
        'USER': env.str('DB_USER', default='postgres'),
        'PASSWORD': env.str('DB_PASSWORD', default='postgres'),
        'HOST': env.str('DB_HOST', default='db'),
        'PORT': 5432,
    }
}

AUTH_USER_MODEL = 'nursing.User'

# For Django>4 csrf token
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000', # This is the one
    'http://0.0.0.0',
    'http://localhost',
    'http://www.localhost'
]

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'  #'es-ar' 

TIME_ZONE = 'Etc/GMT+3'  # 'UTC'  #'America/Argentina/Buenos_Aires'   

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = 'static/'

# Images are saved in '/nursing/media/'

MEDIA_URL= 'media/'
MEDIA_ROOT= os.path.join(BASE_DIR + '/static/', 'media') # Ojo

# React static files
STATIC_ROOT = os.path.join(BASE_DIR ,'static')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'nursing/static'),
    os.path.join(BASE_DIR, 'nursing_react/build/static')
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

""" 
print("BASE_DIR: ", BASE_DIR)
print("STATICFILES_DIRS: ", STATICFILES_DIRS)
print("STATIC_ROOT: ", STATIC_ROOT)
print("STATIC_URL: ", STATIC_URL)
 """